### ISSUE TITLE
Add support for random order expectations

### ISSUE THREAD

**Issue by bilby91** [microsoftly/BotTester#18]
At the moment the array of messages that is used to check responses against a message is used in the order the user provides the message. In some situations, a bot can respond to a message with multiple messages but the order of the messages is not known before hand. I think it would be a good idea to support random order of message, in other words, expect that all the messages are sent from the bot to the user but don't force the same order.

What do you think @microsoftly ?

**Comment by microsoftly** [comment]
Can you give me an example where multiple messages would be sent with a random order? I want to be able to build a test case for it before going into it.

I'm thinking I would end up adding an additional ```sendMessageToBot```. Something like ```sendMessageToBotResponseOrderAgnostic``` or something similar. That then begs the question of how to handle the ```sendMessageToBot``` case where an array for random responses is included.

**Comment by bilby91** [comment]
@microsoftly Sure.

In our use case, a user can start a checkin in Suttna (https://suttna.com) using a command. When running the command the bot will send a message as a reply to the user that executed the command and also direct message every participant of the checkin. The order of the direct messages can be different. 

Make sense ?

**Comment by microsoftly** [comment]
makes sense. I think adding a method ```sendMessageToBotIgnoreResponseOrder``` should do the trick. It won't complicate the api much and still makes sense.

**Comment by microsoftly** [comment]
#23 solved. Will be out in the 3.0.0 release
