### ISSUE TITLE
Ignore responses when sending a message

### ISSUE THREAD

**Issue by bilby91** [microsoftly/BotTester#37]
Hello!

We came up with another use case that could be added to the api. We have some test cases were we don't care about the X replied messages from the bot.

Something like this:

```
new BotTester()
  .sendMessageToBot("Hey", "I", "dont", "care", "about", "this", "messages")
  .sendMessageToBot("Bye" "But I care about this message")
```

I was thinking that maybe we could add something like:

```
new BotTester()
  .sendMessageToBotAndIgnoreResponses("Hey", 6)
  .sendMessageToBot("Bye" "But I care about this message")
```

What do you think @microsoftly ?

CC @santiagodoldan

**Comment by microsoftly** [comment]
I'll have to test it out, but i'm pretty sure doing this works fine:
``` javascript
new BotTester()
  .sendMessageToBot('hey')
  .sendMessageToBot('goodbye', 'adios')
  .runTest()
```

**Comment by bilby91** [comment]
If that works fine their is no need. I'm guessing that the problem would be related to timing with what you describe.

**Comment by microsoftly** [comment]
If you find it's an actual problem in the wild, I'll happily work with/merge a PR

**Comment by santiagodoldan** [comment]
The problem not adding the 6 expectations in that sample is that the next `goodbye` message is sent before getting the other 6 messages, at least in our scenario where messages are sent in different batches. that might call the outgoing callback multiple times and the first should resolve the first promise and execute the second one.
