### ISSUE TITLE
Adaptivecards support

### ISSUE THREAD

**Issue by ubreddy** [microsoftly/BotTester#41]
Now with adaptive cards being available and consoleconnector not supporting adaptivecards is there a way to automate testing for these features?

**Comment by microsoftly** [comment]
I haven't tested with it, but the exported TestConnecter should be able to handle it just fine as long as its passed in as an IMessage. Let me know if that works. I'll try it out sometime soon.

**Comment by microsoftly** [comment]
Sorry about the delay. I just tested locally and and first glance it looks like the test connector doesn't support it. I'll open this up as a feature request. I'll happily look at PRs. I've got less bandwidth around the holidays, but will address this/work with any collaborators as soon as I can.

**Comment by microsoftly** [comment]
#45 feature added
