### ISSUE TITLE
Test case 

### ISSUE THREAD

**Issue by krishan1kamal** [microsoftly/BotTester#42]
Hi i am new with bot any body please provide me detail description how to use this module in unit testing or please provide a working example

**Comment by microsoftly** [comment]
The entire documentation page is a living doc with actual tests. You can check them out [here](https://github.com/microsoftly/BotTester/blob/master/test/BotTester.spec.ts) as well.

Check out the readme to see how to run the tests. 

To see more advanced use cases, look at [this](https://github.com/microsoftly/bot-handoff/blob/simplifyModel/test/AgentHandoff.spec.ts)
