### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by krishan1kamal** [microsoftly/BotTester#43]
'node_modules' is not recognized as an internal or external command,

**Comment by microsoftly** [comment]
Can you give me repro steps?

**Comment by krishan1kamal** [comment]
Can you please guide me what file i need to create inside my test directory and how to configure that file inside package.json file script i am new in testing

**Comment by microsoftly** [comment]
This is a very broad and opinionated question that should be decided by the dev. As long as you install the package with ```npm install --save bot-tester``` or ```yarn add bot-tester``` you should be good to go. Just import and used as described in the docs. I'd recommend cloning this repo and running the tests yourself to see how to make it work.

An additional question, what test runner are you using (e.g. mocha + chai, jasmine, etc ...)?

**Comment by krishan1kamal** [comment]
Thanks

**Comment by krishan1kamal** [comment]
How to write example code in java-script

**Comment by krishan1kamal** [comment]
Hi microsoftly i am using mocha + chai

**Comment by krishan1kamal** [comment]
AssertionError: expected [ Array(1) ] to include undefined i am getting error please help

**Comment by microsoftly** [comment]
```Summary```: it is failing because you're not sending a response/the response is incorrect.

```Actions you can take to verify```: try this in the console or in an emulator and see what happens

```longer answer```:
This means that your bot is not handling the input correctly. You have sent it the message ```Hi``` and it is expecting ```How can I help you. You can say things like : \n\n\- I need to check my leave balance \n\n\- Apply for leave\n\n\ or\n\n- How do I set my goals\n\n- Who can I talk to about performance management``` as a response. 

Instead you did not send a response  or the response you have sent is empty (that's why its undefined). 

I cannot give you any further input without knowing the code driving your bot.

For future submissions, please apply formatting for ease of reading and understanding.

**Comment by krishan1kamal** [comment]
I am getting error please help     
Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

**Comment by microsoftly** [comment]
At the moment, there is not adaptive card support. I will be working on it soon.

**Comment by microsoftly** [comment]
@krishan1kamal Adaptive card support has been added.

#45

**Comment by krishan1kamal** [comment]
Hi @microsoftly  thanks for your support 
I have created my adaptiveCardProvider file 

import { IAdaptiveCard } from 'adaptivecards';
import { IAttachment, IMessage, Message} from 'botbuilder';

export function getAdaptiveCard() : IAdaptiveCard {
  return { 
	"type": "message",
	"attachments": [{
		"contentType": "application/vnd.microsoft.card.adaptive",
		"content": {
			"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
			"type": "AdaptiveCard",
			"body": [{
					"type": "TextBlock",
					"text": "Sure, I can help you withthat. Let me ask few quick questions to help you with that.",
					"weight": "bolder",
					"size": "medium",
					"isSubtle": true,
					"color": "default",
					"horizontalAlignment": "default",
					"wrap": true
				}, {
					"type": "TextBlock",
					"text": "Enter Full Name",
					"weight": "bolder",
					"size": "medium",
					"isSubtle": true,
					"color": "default",
					"horizontalAlignment": "default",
					"wrap": true
				}, {
					"type": "Input.Text",
					"id": "name",
					"isRequired": true,
					"placeholder": "full name"
				},
				{
					"type": "TextBlock",
					"text": "Enter EmployeeId",
					"weight": "bolder",
					"size": "medium",
					"isSubtle": true,
					"color": "default",
					"horizontalAlignment": "default",
					"wrap": true
				}, {
					"type": "Input.Text",
					"id": "employeeId",
					"isRequired": true,
					"placeholder": "employee Id"
				}
			],
			"actions": [{
				"type": "Action.Submit",
				"title": "Submit"
			}]
		}
	}],
	"address": {
		"channelId": "console",
		"user": {
			"id": "user1",
			"name": "user1"
		},
		"bot": {
			"id": "bot",
			"name": "Bot"
		},
		"conversation": {
			"id": "user1Conversation"
		}
	},
	"sentBy": "Bot"
};
}

export function getAdaptiveCardAttachment(adaptiveCard?: IAdaptiveCard): IAttachment {
    adaptiveCard = adaptiveCard || getAdaptiveCard();

    return {
        contentType: 'application/vnd.microsoft.card.adaptive',
        content: adaptiveCard
    };
}

export function getAdaptiveCardMessage(adaptiveCard?: IAdaptiveCard): IMessage {
    return new Message()
        .addAttachment(getAdaptiveCardAttachment(adaptiveCard))
        .toMessage();
}

**Comment by krishan1kamal** [comment]
and i am getting a error 
 1) BotTester Hello:
     **AssertionError: expected** {"type":"message","attachments":[{"contentType":"application/vnd.microsoft.card.adaptive","content":{"$schema":"http://adaptivecards.io
/schemas/adaptive-card.json","type":"AdaptiveCard","body":[{"type":"TextBlock","text":"Sure, I can help you with that. Let me ask few quick questions to help you wit
h that.","weight":"bolder","size":"medium","isSubtle":true,"color":"default","horizontalAlignment":"default","wrap":true},{"type":"TextBlock","text":"Enter Full Name
","weight":"bolder","size":"medium","isSubtle":true,"color":"default","horizontalAlignment":"default","wrap":true},{"type":"Input.Text","id":"name","isRequired":true
,"placeholder":"full name"},{"type":"TextBlock","text":"Enter EmployeeId","weight":"bolder","size":"medium","isSubtle":true,"color":"default","horizontalAlignment":"
default","wrap":true},{"type":"Input.Text","id":"employeeId","isRequired":true,"placeholder":"employee Id"}],"actions":[{"type":"Action.Submit","title":"Submit"}]}}]
,"address":{"channelId":"console","user":{"id":"user1","name":"user1"},"bot":{"id":"bot","name":"Bot"},"conversation":{"id":"user1Conversation"}},"sentBy":"Bot"}
        **to be a subset of one of [**
  {
    "type": "message",
    "agent": "botbuilder",
    "attachments": [
      {

**Comment by microsoftly** [comment]
I do not understand the question. Please refer to the existing rests as reference

**Comment by krishan1kamal** [comment]
I am getting error please help 
Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

**Comment by microsoftly** [comment]
The error is telling you exactly what is happening. The test is timing out. You're either not returning a promise, not calling done, or your expected response is never returned

**Comment by krishan1kamal** [comment]
Hi @microsoftly its mocha timeout i have done with it thanks for your support 
how can i pass multiple adaptive card json? please help
I have a multiple adaptive card in chat bot if i put one adaptive card value other adaptive card is appear i want to validate all adaptive card 

and one more thing i want to know from you how i pass value of adaptive card field as a message 
please help

**Comment by krishan1kamal** [comment]
Hi @microsoftly  i have done with all question thanks for your support
