### ISSUE TITLE
Condition based test

### ISSUE THREAD

**Issue by krishan1kamal** [microsoftly/BotTester#47]
How can i put condition on the behalf of message
and  check conditions based response 
example 
.sendMessageToBot('XYZ','ABC' || 'BCD')
if(bot respone === 'ABC') {
.sendMessageToBot('PQR','PQR')
} else {
.sendMessageToBot('TUV','TUV')
}
Please help

**Comment by microsoftly** [comment]
It seems like you should take the time to ensure you have a proper grasp of the language and using modules with documentation/examples.

Many of your questions suggest you are a novice to the space, which is fine. I would recommend testing heavily locally before submitting questions in the future. To express the point, your example above would throw many syntax errors, let alone not follow the conventions described in the docs, nor does it follow a deterministic model, which your bot should be able to follow within the scope of these tests.

Additionally, you must submit your issues with some amount of formatting. I will start to close your issues in the future if you do not clearly express your intent, formatted, and proof for why a bug exists or clear intent and use for a new feature.

**Comment by krishan1kamal** [comment]
Hi @microsoftly I am sorry for the that i just wanted a condition based validation of message 
if you have a 3 message coming from your bot i need to pass the test if any one of them coming from bot
if you will able to guide me i will be happy
