### ISSUE TITLE
Show custom error messages

### ISSUE THREAD

**Issue by santiagodoldan** [microsoftly/BotTester#51]
For example when comparing simple texts it shows

`AssertionError: expected [ 'a' ] to include 'b.'`

instead of

`AssertionError: Bot should have responded with 'a', but was 'b'`

**Comment by microsoftly** [comment]
Good idea

**Comment by microsoftly** [comment]
Staged and ready for release later today

**Comment by microsoftly** [comment]
published in v3.3.2
