### ISSUE TITLE
@types/bluebird is required

### ISSUE THREAD

**Issue by xtellurian** [microsoftly/BotTester#83]
Installing just BotTester and then compiling tests in Typescript throws the following

```
node_modules/bot-tester/dist/BotTester.d.ts:1:23 - error TS2688: Cannot find type definition file for 'bluebird'.

1 /// <reference types="bluebird" />
```

Workaround: `npm install --save-dev @types/bluebird`

**Comment by microsoftly** [comment]
`@types/bluebird` is already defined as a dev dep. Are you sure it was installed properly the first time?

**Comment by xtellurian** [comment]
True! 
Ignore me 😜
