### ISSUE TITLE
UniversalBot class is missing in botbuilder v4

### ISSUE THREAD

**Issue by jovanmilenkoski** [microsoftly/BotTester#85]
Seems like botbuilder v4 or higher is not supported since there are missing classes there like UniversalBot, ConsoleConnector and etc.

**Comment by microsoftly** [comment]
You should be using the Bobuilder v4 test framework

**Comment by shaikatzir** [comment]
@microsoftly I searched all over the documentation, and couldn't find a way to emulate a connector and inject messages (like `sendMessageToBot`) in botbuilder v4.
Can you please direct me to the right page?

**Comment by microsoftly** [comment]
@shaikatzir I haven't looked into the v4 implementations. I only know that they created a more testable base. I think it can use some extension, but it's much easier to build tests without needing a framework like this.
